"use client";

import { useMemo, useState } from "react";
import { fmtLakh, NumField, ResultRow, SliderField } from "@/components/tools/shared";
import { Card } from "@/components/ui/Card";
import { Tabs } from "@/components/ui/Tabs";

const FREQS = [
  { id: "1", label: "Yearly" },
  { id: "2", label: "Half-yearly" },
  { id: "4", label: "Quarterly" },
  { id: "12", label: "Monthly" },
] as const;

export function CompoundCalculator() {
  const [principal, setPrincipal] = useState(200000);
  const [rate, setRate] = useState(10);
  const [years, setYears] = useState(10);
  const [freq, setFreq] = useState<string>("12");

  const result = useMemo(() => {
    const n = parseInt(freq);
    const amount = principal * Math.pow(1 + rate / 100 / n, n * years);
    return { amount, interest: amount - principal };
  }, [principal, rate, years, freq]);

  return (
    <div className="grid gap-4 lg:grid-cols-2">
      <Card className="space-y-4 p-5">
        <NumField label="Initial amount" value={principal} onChange={setPrincipal} suffix="₹" step={10000} explain="The lump sum you start with." />
        <SliderField label="Annual interest rate" value={rate} onChange={setRate} min={1} max={20} step={0.25} suffix="%" explain="Illustrative rate — real returns vary." />
        <SliderField label="Years" value={years} onChange={setYears} min={1} max={40} step={1} suffix=" yrs" />
        <div>
          <p className="mb-1.5 text-xs font-medium text-secondary">Compounding frequency</p>
          <Tabs items={[...FREQS]} value={freq} onChange={setFreq} size="sm" />
        </div>
        <div className="rounded-xl border border-edge bg-surface2/40 p-4">
          <ResultRow label="Principal" value={fmtLakh(principal)} />
          <ResultRow label="Total interest earned" value={fmtLakh(result.interest)} tone="pos" />
          <ResultRow label="Maturity value" value={fmtLakh(result.amount)} tone="gold" />
        </div>
      </Card>

      <Card className="p-5">
        <p className="section-label mb-3">How compounding grows</p>
        <p className="text-[13px] leading-relaxed text-secondary">
          At {rate}% compounding {FREQS.find((f) => f.id === freq)?.label.toLowerCase()}, your principal of{" "}
          {fmtLakh(principal)} grows to <span className="font-bold text-gold">{fmtLakh(result.amount)}</span> over{" "}
          {years} years. Of that, <span className="font-bold text-pos">{fmtLakh(result.interest)}</span> is interest —
          money generated by money.
        </p>
        <div className="mt-4 space-y-2 rounded-xl border border-gold/20 bg-goldsoft/30 p-4">
          <p className="text-xs font-semibold text-gold">The key insight</p>
          <p className="text-[12.5px] leading-relaxed text-secondary">
            Doubling the time period does far more than doubling the monthly amount. Compounding rewards patience
            disproportionately — which is why starting early is the single most powerful lever.
          </p>
        </div>
      </Card>
    </div>
  );
}
